debug: false  # debug ??? ??, ?? ?? ??? false? ??.
management.endpoints.web.exposure.include: "*"  # actuator ??? ?? ?? api ???

logging:  # ?? ??
  level:
    com.fastcampus.projectboard: debug  # ??? ???? ?? ??? ??
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace  # ????? ? ? ??.(???? ??? ? ??.)

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board  # MySQL ?? 3306 port - 'board' ??????? ??
    username: hrpark  # ?? ??
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    defer-datasource-initialization: true  # ???? ?????? ???? ??? ??  /resources/data.sql ??? ???? ??.
    hibernate.ddl-auto: create  # entity? ?? ???? create table? ????.
    show-sql: true  # sql ?? ????? ?? ?????
    properties:
      hibernate.format_sql: true  # ?? ??? hibernate properties  ? ?? ??? debug query?? ??? ???.
      hibernate.default_batch_fetch_size: 100  # ??? ??? ???? ??? ??
  sql.init.mode: always
  data.rest:
    base-path: /api
    detection-strategy: annotated
  thymeleaf3.decoupled-logic: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_OAUTH_CLIENT_ID}
            client-secret: ${KAKAO_OAUTH_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            client-authentication-method: POST
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

            ##########
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: NEVER

---

spring:
  config.activate.on-profile: heroku
  datasource:
    url: ${JAWSDB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa.hibernate.ddl-auto: create
  sql.init.mode: always  # /resources/data.sql ?? ??? ???? NEVER, ALWAYS, EMBEDDED

---

spring:
  config.activate.on-profile: test  # test db? Activate ????? ??? ???.
  datasource.url: jdbc:h2:mem:testdb